#export PATH="/Applications/ConTeXt/tex/texmf-osx-64/bin:$PATH"
export PATH="/Applications/CMake.app/Contents/bin:$PATH"
export PATH="/Applications/Doxygen.app/Contents/Resources:$PATH"
export PATH="/Applications/Skim.app/Contents/MacOS:$PATH"
export PATH="/Users/adrien/Developer/bin:$PATH"
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/mysql/bin:$PATH"
